# Generated by Django 3.1 on 2021-07-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210723_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
