# Generated by Django 3.1 on 2021-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_published'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('name',)},
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=1000)),
                ('dept_desc', models.CharField(max_length=1000)),
            ],
            options={
                'unique_together': {('dept_name',)},
            },
        ),
    ]
